### ISSUE TITLE
Question About C++ Version Used in SCUDA

### ISSUE THREAD

**Issue by hasanisaeed** [kevmo314/scuda#42]
Hello,

I recently cloned the SCUDA  and am trying to build and run the project. However, I'm unsure which version of C++ the project is compatible with.

I attempted to compile using `C++11` with the following command:

```bash
nvcc -std=c++11 -o $server_out_path $server_path -lnvidia-ml -lcuda
```

I encountered this error:

```css
saeed@saeed:~/github/scuda$ ./local.sh server
building server...
/usr/include/c++/11/bits/std_function.h:435:145: error: parameter packs not expanded with '...':
  435 |         function(_Functor&& __f)
      |                                                                                                                                                 ^ 
/usr/include/c++/11/bits/std_function.h:435:145: note:         '_ArgTypes'
/usr/include/c++/11/bits/std_function.h:530:146: error: parameter packs not expanded with '...':
  530 |         operator=(_Functor&& __f)
      |                                                                                                                                                  ^ 
/usr/include/c++/11/bits/std_function.h:530:146: note:         '_ArgTypes'

```
I also tried compiling with `C++14` and `C++17`, but I ran into other issues as well.

Could you please clarify which C++ standard is being used for this project? Any guidance or tips would be greatly appreciated!

---
For your reference, I’m using the following environment:

**CUDA Version:** 11.5  // I guess that you are most likely using CUDA 12 🤔
**NVCC Version:**
```bash
nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Thu_Nov_18_09:45:30_PST_2021
Cuda compilation tools, release 11.5, V11.5.119
Build cuda_11.5.r11.5/compiler.30672275_0
```

**Operating System:** Ubuntu 22.04
**g++ Version**: 

```bash
g++ --version
g++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
```

---
Thank you for your help!

Best regards,
Saeed

**Comment by kevmo314** [comment]
I believe we are compiling with C++23 as the `g++` version on our dev server is 13.2.0. You are correct that we are currently basing off of CUDA 12.

Unfortunately we haven't had much time to dedicate towards backwards compatibility but we'd welcome any patches to improve compatibility -- generally we are not using any newer language features and write in a more C way, the use of C++ is pretty minimal, so hopefully the changes are not too complex.

**Comment by hasanisaeed** [comment]
Thank you for the clarification! I appreciate the insights on the C++ version and CUDA version compatibility. I'll try updating my g++ to a newer version that supports C++23 and see if that resolves the issue on my end.

Thanks again for your help!
